name: ProyectoX
version: ${project.version}
main: io.chofito.proyectox.ProyectoX
api-version: 1.17
authors: [ Chofito ]
description: A mod with tweaks to improve minecraft difficulty over time
depend: [ helper ]

